/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.mad.letsinvoke

class Invoker {
    fun invoke(): String {
        println("I'm doing my job !!!")
        return "Invoke!!!"
    }
}
