#!/bin/bash -e
cd $(dirname $0)/..

ORIGINAL_TEMPLATE_PATH=./deployment/cloudformation/template.json
COMPILED_TEMPLATE_PATH=./deployment/cloudformation/compiled-template.json

AWS_REGION=cn-north-1
STACK_NAME=letsinvoke
S3_BUCKET=letsinvoke-packages

./gradlew clean
./gradlew jar

aws cloudformation package \
  --region $AWS_REGION \
  --template-file $ORIGINAL_TEMPLATE_PATH \
  --output-template-file $COMPILED_TEMPLATE_PATH \
  --s3-bucket $S3_BUCKET \
  --s3-prefix $STACK_NAME \
  --use-json
